# Generated by Django 3.2.10 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glimpse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glimpsevideocarousel',
            name='desktop_video',
            field=models.FileField(null=True, upload_to='glimpse_videos/desktop/', verbose_name='Glimpse Video for Desktop'),
        ),
        migrations.AddField(
            model_name='glimpsevideocarousel',
            name='mobile_video',
            field=models.FileField(null=True, upload_to='glimpse_videos/mobile/', verbose_name='Glimpse Video for Mobile'),
        ),
    ]
