# Generated by Django 3.2.10 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridalexpert',
            name='desktop_image',
            field=models.ImageField(null=True, upload_to='Bridal_experts/desktop/', verbose_name='Bridal Expert Image for Desktop'),
        ),
        migrations.AddField(
            model_name='bridalexpert',
            name='mobile_image',
            field=models.ImageField(null=True, upload_to='Bridal_experts/mobile/', verbose_name='Bridal Expert Image for Image'),
        ),
    ]
