# Generated by Django 3.2.10 on 2023-01-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('state',
                 models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='booking.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('booking_date', models.DateField(null=True, verbose_name='Service Booking Date')),
                ('message', models.TextField(blank=True, max_length=600, null=True)),
                ('city', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='booking_city', to='booking.city')),
                ('service', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='booking_service', to='booking.service')),
                ('state', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='booking_state', to='booking.state')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
