# Generated by Django 3.2.10 on 2023-01-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    
