# Generated by Django 3.2.10 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridalgallery',
            name='desktop_image',
            field=models.ImageField(null=True, upload_to='bridal_gallery/desktop/', verbose_name='Bridal Gallery Image for Desktop'),
        ),
        migrations.AddField(
            model_name='bridalgallery',
            name='mobile_image',
            field=models.ImageField(null=True, upload_to='bridal_gallery/mobile/', verbose_name='Bridal Gallery Image for Mobile'),
        ),
    ]
