# Generated by Django 3.2.10 on 2023-01-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('description',
                 models.TextField(blank=True, max_length=1000, null=True, verbose_name='Customer Testimonial Review')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
