# Generated by Django 3.2.10 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='desktop_video',
            field=models.FileField(null=True, upload_to='customer_testimonial/desktop/', verbose_name='Customer Testimonial Video for Desktop'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='mobile_video',
            field=models.FileField(null=True, upload_to='customer_testimonial/mobile/', verbose_name='Customer Testimonial Video for Mobile'),
        ),
    ]
